# Form implementation generated from reading ui file 'Designs\CadastrarUser.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CadastrarUsuario(object):
    def setupUi(self, CadastrarUsuario):
        CadastrarUsuario.setObjectName("CadastrarUsuario")
        CadastrarUsuario.resize(400, 300)
        CadastrarUsuario.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:black ;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:grey;\n"
"\n"
"}")
        self.rotuloMenuInicial = QtWidgets.QLabel(parent=CadastrarUsuario)
        self.rotuloMenuInicial.setGeometry(QtCore.QRect(90, 10, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        self.rotuloMenuInicial.setFont(font)
        self.rotuloMenuInicial.setStyleSheet("Color rgb(255, 255, 255)")
        self.rotuloMenuInicial.setObjectName("rotuloMenuInicial")
        self.inputUsuario = QtWidgets.QLineEdit(parent=CadastrarUsuario)
        self.inputUsuario.setGeometry(QtCore.QRect(150, 80, 171, 22))
        self.inputUsuario.setText("")
        self.inputUsuario.setObjectName("inputUsuario")
        self.Usuario = QtWidgets.QLabel(parent=CadastrarUsuario)
        self.Usuario.setGeometry(QtCore.QRect(80, 80, 49, 21))
        self.Usuario.setObjectName("Usuario")
        self.Email = QtWidgets.QLabel(parent=CadastrarUsuario)
        self.Email.setGeometry(QtCore.QRect(80, 140, 49, 21))
        self.Email.setObjectName("Email")
        self.inputEmail = QtWidgets.QLineEdit(parent=CadastrarUsuario)
        self.inputEmail.setGeometry(QtCore.QRect(150, 140, 171, 22))
        self.inputEmail.setText("")
        self.inputEmail.setObjectName("inputEmail")
        self.Senha = QtWidgets.QLabel(parent=CadastrarUsuario)
        self.Senha.setGeometry(QtCore.QRect(80, 200, 49, 21))
        self.Senha.setObjectName("Senha")
        self.inputSenha = QtWidgets.QLineEdit(parent=CadastrarUsuario)
        self.inputSenha.setGeometry(QtCore.QRect(150, 200, 171, 22))
        self.inputSenha.setText("")
        self.inputSenha.setObjectName("inputSenha")
        self.BotaoCadastrar = QtWidgets.QPushButton(parent=CadastrarUsuario)
        self.BotaoCadastrar.setEnabled(True)
        self.BotaoCadastrar.setGeometry(QtCore.QRect(110, 250, 181, 31))
        self.BotaoCadastrar.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: grey;\n"
"}\n"
"")
        self.BotaoCadastrar.setObjectName("BotaoCadastrar")
        self.backButton_2 = QtWidgets.QPushButton(parent=CadastrarUsuario)
        self.backButton_2.setGeometry(QtCore.QRect(330, 0, 75, 24))
        self.backButton_2.setStyleSheet("color: white")
        self.backButton_2.setObjectName("backButton_2")
        self.frame = QtWidgets.QFrame(parent=CadastrarUsuario)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.frame.setMinimumSize(QtCore.QSize(400, 300))
        self.frame.setMaximumSize(QtCore.QSize(400, 300))
        self.frame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.rotuloMenuInicial.raise_()
        self.inputUsuario.raise_()
        self.Usuario.raise_()
        self.Email.raise_()
        self.inputEmail.raise_()
        self.Senha.raise_()
        self.inputSenha.raise_()
        self.BotaoCadastrar.raise_()
        self.backButton_2.raise_()

        self.retranslateUi(CadastrarUsuario)
        QtCore.QMetaObject.connectSlotsByName(CadastrarUsuario)

    def retranslateUi(self, CadastrarUsuario):
        _translate = QtCore.QCoreApplication.translate
        CadastrarUsuario.setWindowTitle(_translate("CadastrarUsuario", "Form"))
        self.rotuloMenuInicial.setText(_translate("CadastrarUsuario", "CADASTRAR USUÁRIO"))
        self.Usuario.setText(_translate("CadastrarUsuario", "<html><head/><body><p><span style=\" font-weight:700;\">Usuário :</span></p></body></html>"))
        self.Email.setText(_translate("CadastrarUsuario", "<html><head/><body><p><span style=\" font-weight:700;\">Email :</span></p></body></html>"))
        self.Senha.setText(_translate("CadastrarUsuario", "<html><head/><body><p><span style=\" font-weight:700;\">Senha : </span></p></body></html>"))
        self.BotaoCadastrar.setText(_translate("CadastrarUsuario", "CADASTRAR"))
        self.backButton_2.setWhatsThis(_translate("CadastrarUsuario", "<html><head/><body><p><span style=\" font-weight:700;\">Voltar</span></p></body></html>"))
        self.backButton_2.setText(_translate("CadastrarUsuario", "Voltar"))
