# Form implementation generated from reading ui file 'Designs\criarPlaylist.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_criarPlay(object):
    def setupUi(self, criarPlay):
        criarPlay.setObjectName("criarPlay")
        criarPlay.resize(400, 300)
        self.rotuloMenuInicial = QtWidgets.QLabel(parent=criarPlay)
        self.rotuloMenuInicial.setGeometry(QtCore.QRect(100, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        self.rotuloMenuInicial.setFont(font)
        self.rotuloMenuInicial.setStyleSheet("Color rgb(255, 255, 255)")
        self.rotuloMenuInicial.setObjectName("rotuloMenuInicial")
        self.label = QtWidgets.QLabel(parent=criarPlay)
        self.label.setGeometry(QtCore.QRect(100, 80, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=criarPlay)
        self.lineEdit.setGeometry(QtCore.QRect(100, 140, 201, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.button_escutarPlay = QtWidgets.QPushButton(parent=criarPlay)
        self.button_escutarPlay.setGeometry(QtCore.QRect(120, 210, 151, 31))
        self.button_escutarPlay.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.button_escutarPlay.setObjectName("button_escutarPlay")

        self.retranslateUi(criarPlay)
        QtCore.QMetaObject.connectSlotsByName(criarPlay)

    def retranslateUi(self, criarPlay):
        _translate = QtCore.QCoreApplication.translate
        criarPlay.setWindowTitle(_translate("criarPlay", "Dialog"))
        self.rotuloMenuInicial.setText(_translate("criarPlay", "CRIAR PLAYLIST"))
        self.label.setText(_translate("criarPlay", "NOME DA PLAYLIST :"))
        self.button_escutarPlay.setText(_translate("criarPlay", "CRIAR PLAYLIST"))
