# Form implementation generated from reading ui file 'Designs\menu_usuario.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_menu_user(object):
    def setupUi(self, menu_user):
        menu_user.setObjectName("menu_user")
        menu_user.resize(400, 300)
        self.rotuloMenuInicial = QtWidgets.QLabel(parent=menu_user)
        self.rotuloMenuInicial.setGeometry(QtCore.QRect(130, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        self.rotuloMenuInicial.setFont(font)
        self.rotuloMenuInicial.setStyleSheet("Color rgb(255, 255, 255)")
        self.rotuloMenuInicial.setObjectName("rotuloMenuInicial")
        self.button_criarPlay = QtWidgets.QPushButton(parent=menu_user)
        self.button_criarPlay.setGeometry(QtCore.QRect(20, 80, 161, 41))
        self.button_criarPlay.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.button_criarPlay.setObjectName("button_criarPlay")
        self.button_verPlay = QtWidgets.QPushButton(parent=menu_user)
        self.button_verPlay.setGeometry(QtCore.QRect(220, 80, 161, 41))
        self.button_verPlay.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.button_verPlay.setObjectName("button_verPlay")
        self.button_historico = QtWidgets.QPushButton(parent=menu_user)
        self.button_historico.setGeometry(QtCore.QRect(20, 140, 161, 41))
        self.button_historico.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.button_historico.setObjectName("button_historico")
        self.button_escutarPlay = QtWidgets.QPushButton(parent=menu_user)
        self.button_escutarPlay.setGeometry(QtCore.QRect(220, 140, 161, 41))
        self.button_escutarPlay.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.button_escutarPlay.setObjectName("button_escutarPlay")
        self.button_sair = QtWidgets.QPushButton(parent=menu_user)
        self.button_sair.setGeometry(QtCore.QRect(20, 210, 361, 41))
        self.button_sair.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.button_sair.setObjectName("button_sair")

        self.retranslateUi(menu_user)
        QtCore.QMetaObject.connectSlotsByName(menu_user)

    def retranslateUi(self, menu_user):
        _translate = QtCore.QCoreApplication.translate
        menu_user.setWindowTitle(_translate("menu_user", "Dialog"))
        self.rotuloMenuInicial.setText(_translate("menu_user", "MENU USUÁRIO"))
        self.button_criarPlay.setText(_translate("menu_user", "CRIAR PLAYLIST"))
        self.button_verPlay.setText(_translate("menu_user", "VER PLAYLISTS"))
        self.button_historico.setText(_translate("menu_user", "HISTÓRICO"))
        self.button_escutarPlay.setText(_translate("menu_user", "ESCUTAR PLAYLIST"))
        self.button_sair.setText(_translate("menu_user", "SAIR"))
