# Form implementation generated from reading ui file 'Designs\menu_usuario.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_menu_user(object):
    def setupUi(self, menu_user):
        menu_user.setObjectName("menu_user")
        menu_user.resize(400, 300)
        menu_user.setStyleSheet("QPushButton{\n"
"background-color:black ;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:grey;\n"
"\n"
"}")
        self.rotuloMenuInicial = QtWidgets.QLabel(parent=menu_user)
        self.rotuloMenuInicial.setGeometry(QtCore.QRect(120, 40, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        self.rotuloMenuInicial.setFont(font)
        self.rotuloMenuInicial.setStyleSheet("Color rgb(255, 255, 255)")
        self.rotuloMenuInicial.setObjectName("rotuloMenuInicial")
        self.button_criarPlay = QtWidgets.QPushButton(parent=menu_user)
        self.button_criarPlay.setGeometry(QtCore.QRect(20, 110, 171, 41))
        self.button_criarPlay.setStyleSheet("color: white;\n"
"border-radius: 10px;\n"
"\n"
"QPushButton{\n"
"background-color:black ;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:grey;\n"
"\n"
"}")
        self.button_criarPlay.setObjectName("button_criarPlay")
        self.button_escutarPlay = QtWidgets.QPushButton(parent=menu_user)
        self.button_escutarPlay.setGeometry(QtCore.QRect(210, 110, 171, 41))
        self.button_escutarPlay.setStyleSheet("color: white;\n"
"border-radius: 10px;\n"
"\n"
"QPushButton{\n"
"background-color:black ;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:grey;\n"
"\n"
"}\n"
"")
        self.button_escutarPlay.setObjectName("button_escutarPlay")
        self.button_sair = QtWidgets.QPushButton(parent=menu_user)
        self.button_sair.setGeometry(QtCore.QRect(20, 160, 361, 41))
        self.button_sair.setStyleSheet("color: white;\n"
"border-radius: 10px;\n"
"\n"
"QPushButton{\n"
"background-color:black ;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:grey;\n"
"\n"
"}")
        self.button_sair.setObjectName("button_sair")
        self.backButton_4 = QtWidgets.QPushButton(parent=menu_user)
        self.backButton_4.setGeometry(QtCore.QRect(130, 250, 151, 31))
        self.backButton_4.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: grey;\n"
"}")
        self.backButton_4.setObjectName("backButton_4")
        self.frame = QtWidgets.QFrame(parent=menu_user)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.frame.setMinimumSize(QtCore.QSize(400, 300))
        self.frame.setMaximumSize(QtCore.QSize(400, 300))
        self.frame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.rotuloMenuInicial.raise_()
        self.button_criarPlay.raise_()
        self.button_escutarPlay.raise_()
        self.button_sair.raise_()
        self.backButton_4.raise_()

        self.retranslateUi(menu_user)
        QtCore.QMetaObject.connectSlotsByName(menu_user)

    def retranslateUi(self, menu_user):
        _translate = QtCore.QCoreApplication.translate
        menu_user.setWindowTitle(_translate("menu_user", "Dialog"))
        self.rotuloMenuInicial.setText(_translate("menu_user", "<html><head/><body><p align=\"center\">MENU USUÁRIO</p></body></html>"))
        self.button_criarPlay.setText(_translate("menu_user", "CRIAR PLAYLIST"))
        self.button_escutarPlay.setText(_translate("menu_user", "ESCUTAR PLAYLIST"))
        self.button_sair.setText(_translate("menu_user", "SAIR"))
        self.backButton_4.setWhatsThis(_translate("menu_user", "<html><head/><body><p><span style=\" font-weight:700;\">Voltar</span></p></body></html>"))
        self.backButton_4.setText(_translate("menu_user", "VOLTAR"))
