# Form implementation generated from reading ui file 'Designs\menuPYQT.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MenuInicial(object):
    def setupUi(self, MenuInicial):
        MenuInicial.setObjectName("MenuInicial")
        MenuInicial.resize(400, 300)
        MenuInicial.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"}")
        self.widget = QtWidgets.QWidget(parent=MenuInicial)
        self.widget.setGeometry(QtCore.QRect(9, 9, 382, 282))
        font = QtGui.QFont()
        font.setBold(False)
        self.widget.setFont(font)
        self.widget.setStyleSheet("QPushButton{\n"
"background-color:black ;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:grey;\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.rotuloMenuInicial = QtWidgets.QLabel(parent=self.widget)
        self.rotuloMenuInicial.setGeometry(QtCore.QRect(80, 0, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        self.rotuloMenuInicial.setFont(font)
        self.rotuloMenuInicial.setStyleSheet("Color rgb(255, 255, 255)")
        self.rotuloMenuInicial.setObjectName("rotuloMenuInicial")
        self.botaoCadastrar = QtWidgets.QPushButton(parent=self.widget)
        self.botaoCadastrar.setGeometry(QtCore.QRect(100, 40, 171, 51))
        self.botaoCadastrar.setStyleSheet("color: white\n"
"")
        self.botaoCadastrar.setObjectName("botaoCadastrar")
        self.botaoEntrar = QtWidgets.QPushButton(parent=self.widget)
        self.botaoEntrar.setGeometry(QtCore.QRect(100, 100, 171, 51))
        self.botaoEntrar.setStyleSheet("COLOR : white")
        self.botaoEntrar.setObjectName("botaoEntrar")
        self.botaoRemover = QtWidgets.QPushButton(parent=self.widget)
        self.botaoRemover.setGeometry(QtCore.QRect(100, 160, 171, 51))
        self.botaoRemover.setStyleSheet("COLOR : white")
        self.botaoRemover.setObjectName("botaoRemover")
        self.botaoSair = QtWidgets.QPushButton(parent=self.widget)
        self.botaoSair.setGeometry(QtCore.QRect(100, 220, 171, 51))
        self.botaoSair.setStyleSheet("COLOR: rgb(255, 0, 0)")
        self.botaoSair.setObjectName("botaoSair")

        self.retranslateUi(MenuInicial)
        QtCore.QMetaObject.connectSlotsByName(MenuInicial)

    def retranslateUi(self, MenuInicial):
        _translate = QtCore.QCoreApplication.translate
        MenuInicial.setWindowTitle(_translate("MenuInicial", "Form"))
        self.rotuloMenuInicial.setText(_translate("MenuInicial", "MENU SPOTI-NINHO"))
        self.botaoCadastrar.setText(_translate("MenuInicial", "CADASTRAR USUÁRIO"))
        self.botaoEntrar.setText(_translate("MenuInicial", "ENTRAR"))
        self.botaoRemover.setText(_translate("MenuInicial", "REMOVER USUÁRIO"))
        self.botaoSair.setText(_translate("MenuInicial", "SAIR"))
