# Form implementation generated from reading ui file 'Designs\musicas.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_musicas(object):
    def setupUi(self, musicas):
        musicas.setObjectName("musicas")
        musicas.resize(400, 300)
        self.rotuloMenuInicial = QtWidgets.QLabel(parent=musicas)
        self.rotuloMenuInicial.setGeometry(QtCore.QRect(150, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        self.rotuloMenuInicial.setFont(font)
        self.rotuloMenuInicial.setStyleSheet("Color rgb(255, 255, 255)")
        self.rotuloMenuInicial.setObjectName("rotuloMenuInicial")
        self.beggin = QtWidgets.QPushButton(parent=musicas)
        self.beggin.setGeometry(QtCore.QRect(40, 80, 141, 21))
        self.beggin.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.beggin.setObjectName("beggin")
        self.AnjoAzul = QtWidgets.QPushButton(parent=musicas)
        self.AnjoAzul.setGeometry(QtCore.QRect(40, 120, 141, 21))
        self.AnjoAzul.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.AnjoAzul.setObjectName("AnjoAzul")
        self.Troco = QtWidgets.QPushButton(parent=musicas)
        self.Troco.setGeometry(QtCore.QRect(40, 160, 141, 21))
        self.Troco.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.Troco.setObjectName("Troco")
        self.Intheend = QtWidgets.QPushButton(parent=musicas)
        self.Intheend.setGeometry(QtCore.QRect(40, 200, 141, 21))
        self.Intheend.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.Intheend.setObjectName("Intheend")
        self.Icarly = QtWidgets.QPushButton(parent=musicas)
        self.Icarly.setGeometry(QtCore.QRect(40, 240, 141, 21))
        self.Icarly.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.Icarly.setObjectName("Icarly")
        self.Medobobo = QtWidgets.QPushButton(parent=musicas)
        self.Medobobo.setGeometry(QtCore.QRect(220, 240, 141, 21))
        self.Medobobo.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.Medobobo.setObjectName("Medobobo")
        self.Dancin = QtWidgets.QPushButton(parent=musicas)
        self.Dancin.setGeometry(QtCore.QRect(220, 160, 141, 21))
        self.Dancin.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.Dancin.setObjectName("Dancin")
        self.blue = QtWidgets.QPushButton(parent=musicas)
        self.blue.setGeometry(QtCore.QRect(220, 80, 141, 21))
        self.blue.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.blue.setObjectName("blue")
        self.Sunshine = QtWidgets.QPushButton(parent=musicas)
        self.Sunshine.setGeometry(QtCore.QRect(220, 120, 141, 21))
        self.Sunshine.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.Sunshine.setObjectName("Sunshine")
        self.Eduard = QtWidgets.QPushButton(parent=musicas)
        self.Eduard.setGeometry(QtCore.QRect(220, 200, 141, 21))
        self.Eduard.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.Eduard.setObjectName("Eduard")

        self.retranslateUi(musicas)
        QtCore.QMetaObject.connectSlotsByName(musicas)

    def retranslateUi(self, musicas):
        _translate = QtCore.QCoreApplication.translate
        musicas.setWindowTitle(_translate("musicas", "Dialog"))
        self.rotuloMenuInicial.setText(_translate("musicas", "MUSICAS"))
        self.beggin.setText(_translate("musicas", "Beggin"))
        self.AnjoAzul.setText(_translate("musicas", "Anjo Azul"))
        self.Troco.setText(_translate("musicas", "Troco de calçada"))
        self.Intheend.setText(_translate("musicas", "In The End"))
        self.Icarly.setText(_translate("musicas", "Tema Icarly"))
        self.Medobobo.setText(_translate("musicas", "Medo bobo"))
        self.Dancin.setText(_translate("musicas", "Dancin"))
        self.blue.setText(_translate("musicas", "Blue Bird"))
        self.Sunshine.setText(_translate("musicas", "Sunshine"))
        self.Eduard.setText(_translate("musicas", "Eduardo e Mônica"))
