# Form implementation generated from reading ui file 'Designs\TelaLogin.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TelaLogin(object):
    def setupUi(self, TelaLogin):
        TelaLogin.setObjectName("TelaLogin")
        TelaLogin.resize(400, 300)
        self.rotuloMenuInicial = QtWidgets.QLabel(parent=TelaLogin)
        self.rotuloMenuInicial.setGeometry(QtCore.QRect(120, 20, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        self.rotuloMenuInicial.setFont(font)
        self.rotuloMenuInicial.setStyleSheet("Color rgb(255, 255, 255)")
        self.rotuloMenuInicial.setObjectName("rotuloMenuInicial")
        self.inputUsuario = QtWidgets.QLineEdit(parent=TelaLogin)
        self.inputUsuario.setGeometry(QtCore.QRect(140, 120, 171, 22))
        self.inputUsuario.setText("")
        self.inputUsuario.setObjectName("inputUsuario")
        self.Usuario = QtWidgets.QLabel(parent=TelaLogin)
        self.Usuario.setGeometry(QtCore.QRect(80, 120, 49, 21))
        self.Usuario.setObjectName("Usuario")
        self.inputSenha = QtWidgets.QLineEdit(parent=TelaLogin)
        self.inputSenha.setGeometry(QtCore.QRect(140, 180, 171, 22))
        self.inputSenha.setText("")
        self.inputSenha.setObjectName("inputSenha")
        self.Senha = QtWidgets.QLabel(parent=TelaLogin)
        self.Senha.setGeometry(QtCore.QRect(80, 180, 49, 21))
        self.Senha.setObjectName("Senha")
        self.BotaoLogin = QtWidgets.QPushButton(parent=TelaLogin)
        self.BotaoLogin.setGeometry(QtCore.QRect(130, 240, 131, 31))
        self.BotaoLogin.setStyleSheet("background-color: black;\n"
"color:  white;\n"
"border-radius: 10px\n"
"")
        self.BotaoLogin.setObjectName("BotaoLogin")

        self.retranslateUi(TelaLogin)
        QtCore.QMetaObject.connectSlotsByName(TelaLogin)

    def retranslateUi(self, TelaLogin):
        _translate = QtCore.QCoreApplication.translate
        TelaLogin.setWindowTitle(_translate("TelaLogin", "Form"))
        self.rotuloMenuInicial.setText(_translate("TelaLogin", "<html><head/><body><p><span style=\" font-size:20pt;\">Bem vindo !</span></p></body></html>"))
        self.Usuario.setText(_translate("TelaLogin", "Usuário :"))
        self.Senha.setText(_translate("TelaLogin", "Senha : "))
        self.BotaoLogin.setText(_translate("TelaLogin", "Login"))
