# Form implementation generated from reading ui file 'Designs\TelaLogin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TelaLogin(object):
    def setupUi(self, TelaLogin):
        TelaLogin.setObjectName("TelaLogin")
        TelaLogin.resize(400, 300)
        TelaLogin.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:black ;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:grey;\n"
"\n"
"}")
        self.inputUsuario = QtWidgets.QLineEdit(parent=TelaLogin)
        self.inputUsuario.setGeometry(QtCore.QRect(140, 120, 171, 22))
        self.inputUsuario.setText("")
        self.inputUsuario.setObjectName("inputUsuario")
        self.Usuario = QtWidgets.QLabel(parent=TelaLogin)
        self.Usuario.setGeometry(QtCore.QRect(80, 120, 49, 21))
        self.Usuario.setObjectName("Usuario")
        self.inputSenha = QtWidgets.QLineEdit(parent=TelaLogin)
        self.inputSenha.setGeometry(QtCore.QRect(140, 180, 171, 22))
        self.inputSenha.setText("")
        self.inputSenha.setObjectName("inputSenha")
        self.Senha = QtWidgets.QLabel(parent=TelaLogin)
        self.Senha.setGeometry(QtCore.QRect(80, 180, 49, 21))
        self.Senha.setObjectName("Senha")
        self.BotaoLogin = QtWidgets.QPushButton(parent=TelaLogin)
        self.BotaoLogin.setGeometry(QtCore.QRect(130, 240, 131, 31))
        self.BotaoLogin.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: grey;\n"
"}\n"
"")
        self.BotaoLogin.setObjectName("BotaoLogin")
        self.rotuloMenuInicial_2 = QtWidgets.QLabel(parent=TelaLogin)
        self.rotuloMenuInicial_2.setGeometry(QtCore.QRect(170, 30, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        self.rotuloMenuInicial_2.setFont(font)
        self.rotuloMenuInicial_2.setStyleSheet("Color rgb(255, 255, 255)")
        self.rotuloMenuInicial_2.setObjectName("rotuloMenuInicial_2")
        self.backButton_2 = QtWidgets.QPushButton(parent=TelaLogin)
        self.backButton_2.setGeometry(QtCore.QRect(330, 0, 75, 24))
        self.backButton_2.setStyleSheet("color: white")
        self.backButton_2.setObjectName("backButton_2")
        self.frame = QtWidgets.QFrame(parent=TelaLogin)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.frame.setMinimumSize(QtCore.QSize(400, 300))
        self.frame.setMaximumSize(QtCore.QSize(400, 300))
        self.frame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.inputUsuario.raise_()
        self.Usuario.raise_()
        self.inputSenha.raise_()
        self.Senha.raise_()
        self.BotaoLogin.raise_()
        self.rotuloMenuInicial_2.raise_()
        self.backButton_2.raise_()

        self.retranslateUi(TelaLogin)
        QtCore.QMetaObject.connectSlotsByName(TelaLogin)

    def retranslateUi(self, TelaLogin):
        _translate = QtCore.QCoreApplication.translate
        TelaLogin.setWindowTitle(_translate("TelaLogin", "Form"))
        self.Usuario.setText(_translate("TelaLogin", "<html><head/><body><p><span style=\" font-weight:700;\">Usuário :</span></p></body></html>"))
        self.Senha.setText(_translate("TelaLogin", "<html><head/><body><p><span style=\" font-weight:700;\">Senha : </span></p></body></html>"))
        self.BotaoLogin.setText(_translate("TelaLogin", "Login"))
        self.rotuloMenuInicial_2.setText(_translate("TelaLogin", "LOGIN"))
        self.backButton_2.setWhatsThis(_translate("TelaLogin", "<html><head/><body><p><span style=\" font-weight:700;\">Voltar</span></p></body></html>"))
        self.backButton_2.setText(_translate("TelaLogin", "Voltar"))
