# Form implementation generated from reading ui file 'Designs\TelaRemover.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TelaRemover(object):
    def setupUi(self, TelaRemover):
        TelaRemover.setObjectName("TelaRemover")
        TelaRemover.resize(400, 300)
        self.rotuloMenuInicial = QtWidgets.QLabel(parent=TelaRemover)
        self.rotuloMenuInicial.setGeometry(QtCore.QRect(90, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        self.rotuloMenuInicial.setFont(font)
        self.rotuloMenuInicial.setStyleSheet("Color rgb(255, 255, 255)")
        self.rotuloMenuInicial.setObjectName("rotuloMenuInicial")
        self.Email = QtWidgets.QLabel(parent=TelaRemover)
        self.Email.setGeometry(QtCore.QRect(80, 140, 49, 21))
        self.Email.setObjectName("Email")
        self.BotaoRemover = QtWidgets.QPushButton(parent=TelaRemover)
        self.BotaoRemover.setGeometry(QtCore.QRect(130, 240, 131, 31))
        self.BotaoRemover.setStyleSheet("background-color: black;\n"
"color:  white;\n"
"border-radius: 10px\n"
"")
        self.BotaoRemover.setObjectName("BotaoRemover")
        self.inputEmail = QtWidgets.QLineEdit(parent=TelaRemover)
        self.inputEmail.setGeometry(QtCore.QRect(140, 140, 171, 22))
        self.inputEmail.setText("")
        self.inputEmail.setObjectName("inputEmail")

        self.retranslateUi(TelaRemover)
        QtCore.QMetaObject.connectSlotsByName(TelaRemover)

    def retranslateUi(self, TelaRemover):
        _translate = QtCore.QCoreApplication.translate
        TelaRemover.setWindowTitle(_translate("TelaRemover", "Form"))
        self.rotuloMenuInicial.setText(_translate("TelaRemover", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Remover Usuario</span></p></body></html>"))
        self.Email.setText(_translate("TelaRemover", "Email :"))
        self.BotaoRemover.setText(_translate("TelaRemover", "Remover"))
